#! /bin/sh

#
# CONFIGURATION SECTION
#
if [ -z "$PIC30_CD" ]; then
    echo "Environmental variable PIC30_CD must be set up.";
    exit 1;
fi

GAS30="$PIC30_CD/bin/pic30-as -W"
GLD30=$PIC30_CD/bin/pic30-ld

#
# END CONFIGURATION
#

# process args
vflag=off
while [ $# -gt 0 ]
do
    case "$1" in
        -v)  vflag=on;;
    esac
    shift
done

rm -f t1.o
$GAS30 -o t1.o -p30F6014 t1.s
err=$?
if [ $vflag = "on" ]; then
    echo
    echo "$GAS30 -o t1.o -p30F6014 t1.s"
    echo $err
fi


rm -f t.exe t.map
$GLD30 -o t.exe -p24FJ128GA006 t1.o --force-link > temp 2>&1
err=$?
if [ $vflag = "on" ]; then
    echo
    echo "$GLD30 -o t.exe -p24FJ128GA006 t1.o --force-link "
    echo $err
    echo
fi

echo
echo `head -1 info.txt`

if [ $? -ne 0 ]; then
    echo "ERRORs Detected!!"
    echo
    exit 199
fi

echo "All Tests Pass"
echo
exit 0
