#name:  Listing - 3 bytes of program memory for each offset
#as: -a
MPLAB ASM30 Listing:  .*utc1123\.s 			page 1


   1              	        .text
   2 000000  80 00 78 	        mov w0,w1
   3 000002  01 01 78 	        mov w1,w2
MPLAB ASM30 Listing:  .*utc1123\.s 			page 2


DEFINED SYMBOLS
                            \*ABS\*:00000001 __C30ELF

NO UNDEFINED SYMBOLS

EQUATE SYMBOLS
                        __C30ELF = 0x1
