#name:  Listing - data memory addresses are 16 bits
#as: -a
MPLAB ASM30 Listing:  .*utc1125\.s 			page 1


   1              	        .data
   2 0000 01 02       	        .byte 1,2
MPLAB ASM30 Listing:  .*utc1125\.s 			page 2


DEFINED SYMBOLS
                            \*ABS\*:00000000 fake
                            \*ABS\*:00000001 __C30COFF

NO UNDEFINED SYMBOLS

EQUATE SYMBOLS
                       __C30COFF = 0x1
