#name:  Listing - program memory addresses are 24 bits
#as: -a
MPLAB ASM30 Listing:  .*utc1124\.s 			page 1


   1              	        .text
   2 000000  01 02 00 	        .byte 1,2
MPLAB ASM30 Listing:  .*utc1124\.s 			page 2


DEFINED SYMBOLS
                            \*ABS\*:00000000 fake
                            \*ABS\*:00000001 __C30COFF

NO UNDEFINED SYMBOLS

EQUATE SYMBOLS
                       __C30COFF = 0x1
