#name:  Listing - labels are displayed on new line, after padding
#as: -a
MPLAB ASM30 Listing:  .*utc1128.s 			page 1


   1              	        .text
   2 000000  01 00 00 	        .pbyte 1
   3              	L1:
   4 000002  02 03 04 	        .pbyte 2,3,4
MPLAB ASM30 Listing:  .*utc1128.s 			page 2


DEFINED SYMBOLS
                            \*ABS\*:00000001 __C30ELF
.*utc1128.s:3      .text:00000002 L1

NO UNDEFINED SYMBOLS

EQUATE SYMBOLS
                        __C30ELF = 0x1
