#name:  Listing - only valid PC addresses are displayed
#as: -a
MPLAB ASM30 Listing:  .*utc1122\.s 			page 1


   1              	        .text
   2 000000  01 02 03 	        .pbyte 1,2,3,4,5
   2         04 05 
   3               06 	        .pbyte 6,7,8,9
   3 000004  07 08 09 
MPLAB ASM30 Listing:  .*utc1122.s 			page 2


DEFINED SYMBOLS
                            \*ABS\*:00000001 __C30ELF

NO UNDEFINED SYMBOLS

EQUATE SYMBOLS
                        __C30ELF = 0x1
