#! /bin/sh

#
# CONFIGURATION SECTION
#
if [ -z "$PIC30_CD" ]; then
    echo "Environmental variable PIC30_CD must be set up.";
    exit 1;
fi

GAS30="$PIC30_CD/bin/xc16-as -W"
GLD30=$PIC30_CD/bin/xc16-ld
OBJDUMP=$PIC30_CD/bin/xc16-objdump
LIB_PATH=$PIC30_CD/lib

#
# convert paths to DOS, if necessary
#
HOST=`uname`
if ( echo $HOST | grep -i "cygwin" > /dev/null 2>&1 ) ; then
  HOST="cygwin"
  LIB_PATH=`cygpath -m $LIB_PATH`
fi

#
# END CONFIGURATION
#

# process args
vflag=off
while [ $# -gt 0 ]
do
    case "$1" in
        -v)  vflag=on;;
    esac
    shift
done

rm -f t1.o
$GAS30 -o t1.o t1.s
err=$?
if [ $vflag = "on" ]; then
    echo
    echo "$GAS30 -o t1.o t1.s"
    echo $err
fi

rm -f t.exe t.map
$GLD30 -o t.exe t1.o -L $LIB_PATH -lpic30 --data-init -Map=t.map > temp 2>&1
err=$?
if [ $vflag = "on" ]; then
    echo
    echo "$GLD30 -o t.exe t1.o -L $LIB_PATH -lpic30 --data-init -Map=t.map"
    cat temp
    echo $err
    echo
fi

rm -f temp
$OBJDUMP -h t.exe > temp
err=$?
if [ $vflag = "on" ]; then
    echo
    echo "$OBJDUMP -h t.exe > temp"
    echo $err
    echo
fi

# extract the size of section .dinit
LINE1=`perl -n -e 'if (/^Idx (.*Size).*$/) {print "    $1\n"}' temp`
LINE2=`perl -n -e 'if (/.*(\.dinit\s+\w+).*$/) {print "    $1\n"}' temp`

# build an output file
rm -f test.out
{
    echo
    echo "Excerpt from xc16-objdump output:"
    echo
    echo "$LINE1"
    echo "$LINE2"
    echo
} > test.out

if [ $vflag = "on" ]; then
    cat test.out
fi

echo
echo `head -1 info.txt`

if [ $vflag = "on" ]; then
    diff -b -B test.out expect.out
else
    diff -b -B test.out expect.out > /dev/null
fi

if [ $? -ne 0 ]; then
    echo "ERRORs Detected!!"
    echo
    exit 199
fi

echo "All Tests Pass"
echo
exit 0
