#! /bin/sh

#
# CONFIGURATION SECTION
#
if [ -z "$PIC30_CD" ]; then
    echo "Environmental variable PIC30_CD must be set up.";
    exit 1;
fi

GAS30="$PIC30_CD/bin/xc16-as -omf=coff -W"
GLD30="$PIC30_CD/bin/xc16-ld -omf=coff"
OBJDUMP="$PIC30_CD/bin/xc16-objdump -omf=coff"

#
# END CONFIGURATION
#

# process args
vflag=off
while [ $# -gt 0 ]
do
    case "$1" in
        -v)  vflag=on;;
    esac
    shift
done

rm -f t1.o
$GAS30 -o t1.o t1.s 2> /dev/null
err=$?
if [ $vflag = "on" ]; then
    
    echo
    echo "$GAS30 -o t1.o t1.s"
    echo $err
fi

rm -f t.exe
$GLD30 -o t.exe t1.o 2>test.out
err=$?
if [ $vflag = "on" ]; then
    echo "$GLD30 -o t.exe t1.o 2> test.out"
    echo $err
fi

if [ $vflag = "on" ]; then
    echo
    echo "output from the linker:"
    echo
    cat test.out
    echo
fi

echo
echo `head -1 info.txt`

if [ $vflag = "on" ]; then
    diff -b -B test.out expect.out
else
    diff -b -B test.out expect.out > /dev/null
fi


if [ $? -ne 0 ]; then
    echo "ERRORs Detected!!"
    echo
    exit 199
fi

echo "All Tests Pass"
echo
exit 0
