#! /bin/sh

#
# CONFIGURATION SECTION
#
if [ -z "$PIC30_CD" ]; then
    echo "Environmental variable PIC30_CD must be set up.";
    exit 1;
fi

GCC30=$PIC30_CD/bin/pic30-gcc
GAS30="$PIC30_CD/bin/pic30-as -W"
GLD30=$PIC30_CD/bin/pic30-ld
OBJDUMP=$PIC30_CD/bin/pic30-objdump

BIN2HEX=$PIC30_CD/bin/pic30-bin2hex
SIM30=$PIC30_CD/bin/sim30

#
# END CONFIGURATION
#

# process args
vflag=off
while [ $# -gt 0 ]
do
    case "$1" in
        -v)  vflag=on;;
    esac
    shift
done

rm -f t1.o
$GAS30 t1.s -o t1.o
err=$?
if [ $vflag = "on" ]; then
    echo
    echo "$GAS30 t1.s -o t1.o"
    echo $err
    echo
fi

rm -f t.exe
$GLD30 t1.o -o t.exe -Map=t.map
err=$?
if [ $vflag = "on" ]; then
    echo
    echo "$GLD30 t1.o -o t.exe -Map=t.map"
    echo $err
    echo
fi

rm -f temp
$OBJDUMP -h t.exe > temp
err=$?
if [ $vflag = "on" ]; then
    echo
    echo "$OBJDUMP -h t.exe"
    echo $err
    cat temp
    echo
fi

LINE1=`awk '/bss_1000/ { print $2,$3,$4,$5 }' temp`
LINE2=`awk '/ABSOLUTE/ { print $1,$2,$3,$4,$5 }' temp`
LINE3=`awk '/bss_ymem/ { print $2,$3,$4,$5 }' temp`
LINE4=`awk '/YMEMORY/ { print $1,$2,$3,$4,$5 }' temp`

{
echo
echo "excerpt from pic30-objdump (-h option):"
echo
echo "$LINE1"
echo "$LINE2"
echo "$LINE3"
echo "$LINE4"
echo
} > test.out

echo
echo `head -1 info.txt`

diff test.out expect.out
err=$?
if [ $err -ne 0 ]; then
    echo "ERROR Detected!!"
    echo
    exit 99
fi

echo "All Tests Pass"
echo
exit 0
