#! /bin/sh

#
# CONFIGURATION SECTION
#
if [ -z "$PIC30_CD" ]; then
    echo "Environmental variable PIC30_CD must be set up.";
    exit 1;
fi

GCC30="$PIC30_CD/bin/xc16-gcc -omf=coff"
GAS30="$PIC30_CD/bin/xc16-as -omf=coff -W"
GLD30="$PIC30_CD/bin/xc16-ld -omf=coff"
OBJDUMP="$PIC30_CD/bin/xc16-objdump -omf=coff"

BIN2HEX="$PIC30_CD/bin/xc16-bin2hex -omf=coff"
SIM30=$PIC30_CD/bin/sim30

#
# END CONFIGURATION
#

# process args
vflag=off
while [ $# -gt 0 ]
do
    case "$1" in
        -v)  vflag=on;;
    esac
    shift
done

rm -f t1.exe
$GCC30 -o t1.exe t1.c -Wl,--heap=128 || exit 99
err=$?
if [ $vflag = "on" ]; then
    echo
    echo "$GCC30 -o t1.exe t1.c -Wl,--heap=128"
    echo $err
fi

rm -f t1.hex
$BIN2HEX t1.exe > /dev/null
err=$?
if [ $vflag = "on" ]; then
    echo
    echo "$BIN2HEX t1.exe"
    echo $err
fi

# pass a hex file to the simulator
rm -f test.out
$SIM30 run.cmd > /dev/null
err=$?
if [ $vflag = "on" ]; then
    echo
    echo "$SIM30 run.cmd"
    echo $err
fi
echo "testing the hex file:" > test.out
echo >> test.out
cat UartOut.txt >> test.out
rm -f UartOut.txt

# pass an object file to the simulator
$SIM30 run.cmd2 > /dev/null
err=$?
if [ $vflag = "on" ]; then
    echo
    echo "$SIM30 run.cmd2"
    echo $err
fi
echo >> test.out
echo "testing the object file:" >> test.out
echo >> test.out
cat UartOut.txt >> test.out
rm -f UartOut.txt

if [ $vflag = "on" ]; then
    echo
    cat test.out
fi

echo
echo `head -1 info.txt`

if [ $vflag = "on" ]; then
    diff -b -B test.out expect.out
else
    diff -b -B test.out expect.out > /dev/null
fi


if [ $? -ne 0 ]; then
    echo "ERRORs Detected!!"
    echo
    exit 199
fi

echo "All Tests Pass"
echo
exit 0
