#! /bin/sh

#
# CONFIGURATION SECTION
#
if [ -z "$PIC30_CD" ]; then
    echo "Environmental variable PIC30_CD must be set up.";
    exit 1;
fi

GCC30=$PIC30_CD/bin/xc16-gcc
OBJDUMP=$PIC30_CD/bin/xc16-objdump
BIN2HEX=$PIC30_CD/bin/xc16-bin2hex

#
# END CONFIGURATION
#

# process args
vflag=off
while [ $# -gt 0 ]
do
    case "$1" in
        -v)  vflag=on;;
    esac
    shift
done

rm -f t.exe
$GCC30 -o t.exe t1.s || exit 99
err=$?
if [ $vflag = "on" ]; then
    echo "$GCC30 -o t.exe t1.s"
    echo $err
fi

if [ $vflag = "on" ]; then
    $OBJDUMP -s -j .comment t.exe || exit 99
    $BIN2HEX t.exe || exit 99
    echo
fi

rm -f test.out temp
$OBJDUMP -s -j .comment t.exe > test.out
$BIN2HEX t.exe > temp
grep comment temp >> test.out

echo
echo `head -1 info.txt`

if [ $vflag = "on" ]; then
    diff -b -B test.out expect.out
else
    diff -b -B test.out expect.out > /dev/null
fi


if [ $? -ne 0 ]; then
    echo "ERRORs Detected!!"
    echo
    exit 199
fi

echo "All Tests Pass"
echo
exit 0
